spring.application.name=auth-svc
spring.datasource.driver=org.postgresql.Driver
server.port=9090

# Keycloak Configuration
keycloak.realm=foood
keycloak.auth-server-url=http://localhost:8080/
keycloak.resource=auth-svc
keycloak.credentials.secret=ybcEN1aBQaMmRE3QwR0iTP5lUWXRb2jq
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.client-id=admin-cli

spring.security.oauth2.client.registration.keycloak.client-id=auth-svc
spring.security.oauth2.client.registration.keycloak.client-secret=ybcEN1aBQaMmRE3QwR0iTP5lUWXRb2jq
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/foood
